# Generated by Django 2.2.7 on 2019-11-13 00:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_instances', '0002_testinstance_testrun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testinstance',
            name='assignee',
        ),
        migrations.AddField(
            model_name='testinstance',
            name='assignees',
            field=models.ManyToManyField(blank=True, null=True, related_name='test_instances', to=settings.AUTH_USER_MODEL),
        ),
    ]
