# Generated by Django 2.2.6 on 2019-10-31 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("testcases", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="description",
            field=models.TextField(blank=True, null=True),
        )
    ]
