FROM python:3.7.4

ENV PIP_DISABLE_PIP_VERSION_CHECK=on

RUN pip install poetry==0.12.17

COPY . /app/
COPY compose/django/docker-entrypoint-production.sh /docker-entrypoint.sh
WORKDIR /app
RUN poetry config settings.virtualenvs.create false
RUN poetry install --no-dev --no-interaction
RUN chmod +x /docker-entrypoint.sh
